#EW-2442 EW-2443 User creation endpoint added
ejariza-evowill/sentiment-chat-backend pull request #3
Opened 2023-06-30 16:15 UTC by Magnico

Changes made:
- Created endpoint for creating a user
- Created endpoint for retrieving all users
- Added validations for email and username syntax
- Added validations for unique email and username
- Created corresponding tests

2023-07-03 15:38 UTC, jaagomezmu commented on app/routes/user.py
According to the Python code style guidelines known as PEP 8, imports in a Python script should be grouped into three different sections, in the following order:

    a. Imports of standard Python modules.
    b. Third-party module imports.
    c. Imports of local or project-specific modules.
    
    https://peps.python.org/pep-0008/#imports

2023-07-03 15:41 UTC, jaagomezmu approved these changes
Looks good, 
In a next order I would order the imports

2023-07-03 19:36 UTC, ejariza-evowill commented on app/routes/user.py
Please follow these guidelines and implement the corresponding changes @Magnico

2023-07-04 18:58 UTC, ejariza-evowill requested changes

2023-07-04 18:58 UTC, ejariza-evowill commented on app/routes/user.py
.

2023-07-10 14:08 UTC, jaagomezmu approved these changes
looks good!

2023-07-14 18:42 UTC, merged